# DevOps Agent Configuration

# Service settings
service:
  name: lexos-devops-agent
  version: 1.0.0
  environment: production
  log_level: INFO
  metrics_port: 8000

# Database configuration
database:
  host: postgres
  port: 5432
  name: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${DB_PASSWORD}
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800

# Redis configuration
redis:
  host: redis
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5

# Deployment settings
deployment:
  default_timeout: 300
  max_retries: 3
  retry_delay: 10
  health_check_interval: 30
  rollback_on_failure: true
  environments:
    - name: development
      url: http://dev-api.lexos.local
      credentials:
        username: ${DEV_USERNAME}
        password: ${DEV_PASSWORD}
    - name: staging
      url: http://staging-api.lexos.local
      credentials:
        username: ${STAGING_USERNAME}
        password: ${STAGING_PASSWORD}
    - name: production
      url: http://api.lexos.local
      credentials:
        username: ${PROD_USERNAME}
        password: ${PROD_PASSWORD}

# Monitoring settings
monitoring:
  prometheus:
    enabled: true
    path: /metrics
    port: 8000
  health_check:
    interval: 30
    timeout: 5
    retries: 3
  logging:
    level: INFO
    format: json
    output: stdout
    retention: 30d

# Security settings
security:
  ssl:
    enabled: true
    cert_path: /etc/ssl/lexos/cert.pem
    key_path: /etc/ssl/lexos/key.pem
  authentication:
    required: true
    method: jwt
    token_expiry: 3600
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# Resource limits
resources:
  cpu:
    limit: 4
    reservation: 2
  memory:
    limit: 8G
    reservation: 4G
  gpu:
    enabled: true
    device_ids: ${CUDA_VISIBLE_DEVICES}
    memory_limit: 4G

# Backup settings
backup:
  enabled: true
  schedule: "0 0 * * *"  # Daily at midnight
  retention: 30d
  compression: true
  encryption: true
  storage:
    type: s3
    bucket: ${BACKUP_BUCKET}
    region: ${AWS_REGION}
    prefix: lexos/backups

# Alerting settings
alerts:
  enabled: true
  channels:
    - type: email
      recipients:
        - ${ALERT_EMAIL}
    - type: slack
      webhook_url: ${SLACK_WEBHOOK_URL}
  thresholds:
    cpu_usage: 80
    memory_usage: 85
    disk_usage: 90
    gpu_usage: 95
    deployment_failure_rate: 10 