version: '3.8'

services:
  # Core Infrastructure
  redis:
    image: redis:7-alpine
    container_name: lexos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - lexos-network

  postgres:
    image: postgres:15
    container_name: lexos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lexos_consciousness
      POSTGRES_USER: lexos_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lexos-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: lexos-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - lexos-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: lexos-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - lexos-network

  # API Gateway
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-api-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FIGMA_API_KEY=${FIGMA_API_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - lexos-network

  # WebSocket Server
  websocket-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-websocket
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
      - postgres
    networks:
      - lexos-network

  # Consciousness Memory Service
  consciousness-memory:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-consciousness-memory
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - postgres
      - redis
      - qdrant
    networks:
      - lexos-network

  # Autonomous Reasoning Service
  autonomous-reasoning:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-autonomous-reasoning
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - lexos-network

  # Financial Intelligence Service
  financial-intelligence:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-financial-intelligence
    restart: unless-stopped
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLICKHOUSE_URL=http://clickhouse:8123
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - clickhouse
      - redis
    networks:
      - lexos-network

  # Self-Modification Service
  self-modification:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-self-modification
    restart: unless-stopped
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - redis
    networks:
      - lexos-network
    privileged: true

  # Environmental Interaction Service
  environmental-interaction:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-environmental-interaction
    restart: unless-stopped
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - redis
    networks:
      - lexos-network
    privileged: true

  # Creative Expression Service
  creative-expression:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lexos-creative-expression
    restart: unless-stopped
    ports:
      - "8006:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./creative-assets:/app/assets
    depends_on:
      - postgres
      - redis
    networks:
      - lexos-network

networks:
  lexos-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  qdrant_data:
  clickhouse_data:
