version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DOMAIN=lexcommand.ai
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=$Overlord0824
      - REDIS_PASSWORD=secure-redis-pass123
      - ALLOWED_ORIGINS=https://lexcommand.ai
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SSL=false
      - LOG_LEVEL=INFO
    volumes:
      - ./keys:/etc/lexcommand/keys:ro
      - ./logs:/var/log/lexcommand
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - lexcommand-network

  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass secure-redis-pass123
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - lexcommand-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lexcommand-network

networks:
  lexcommand-network:
    driver: bridge

volumes:
  redis-data: