services:
  - type: web
    name: lexos-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://lexcommand.ai,https://www.lexcommand.ai,https://lexcommand.vercel.app,http://localhost:3000
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: REPLICATE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FIGMA_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lexos-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: lexos-redis
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: lexos-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://lexos-backend.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://lexos-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  - type: redis
    name: lexos-redis
    plan: free
    ipAllowList: []

  - type: web
    name: lexos-llm
    env: docker
    dockerfilePath: ./llm-service/Dockerfile
    envVars:
      - key: MODEL_PATH
        value: /app/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
      - key: GPU_ENABLED
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: REPLICATE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: lexos-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.services.analytics:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8002
      - key: DATABASE_URL
        fromDatabase:
          name: lexos-postgres
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: lexos-postgres
    databaseName: lexos
    user: lexos
    plan: free 