service:
  name: "LexOS GIS Service"
  version: "1.0.0"
  environment: "production"
  log_level: "INFO"
  metrics_port: 8000

database:
  postgresql:
    host: "postgres"
    port: 5432
    database: "lexos_gis"
    user: "lexos"
    password: "${POSTGRES_PASSWORD}"
    pool_size: 20
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 1800

redis:
  host: "redis"
  port: 6379
  password: "${REDIS_PASSWORD}"
  max_connections: 100
  socket_timeout: 5
  socket_connect_timeout: 5

geospatial:
  data_processing:
    max_file_size: 100MB
    supported_formats:
      - "GeoJSON"
      - "Shapefile"
      - "KML"
      - "GPX"
      - "CSV"
    coordinate_systems:
      default: "EPSG:4326"
      supported:
        - "EPSG:4326"  # WGS84
        - "EPSG:3857"  # Web Mercator
        - "EPSG:32633" # UTM Zone 33N
    processing:
      max_workers: 4
      chunk_size: 1000
      timeout: 300
      retry_attempts: 3
      retry_delay: 5

  analysis:
    spatial_operations:
      - "intersection"
      - "union"
      - "difference"
      - "buffer"
      - "convex_hull"
      - "centroid"
    statistical_operations:
      - "mean"
      - "median"
      - "standard_deviation"
      - "variance"
      - "percentile"
    clustering:
      algorithms:
        - "k-means"
        - "DBSCAN"
        - "hierarchical"
      max_clusters: 100
      min_samples: 5

  visualization:
    map_styles:
      - "light"
      - "dark"
      - "satellite"
      - "terrain"
    color_schemes:
      - "viridis"
      - "plasma"
      - "inferno"
      - "magma"
    export_formats:
      - "PNG"
      - "JPEG"
      - "PDF"
      - "SVG"

  caching:
    enabled: true
    ttl: 3600
    max_size: 1GB
    strategies:
      - "memory"
      - "redis"
      - "disk"

monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
    scrape_interval: 15s

  health_checks:
    interval: 30s
    timeout: 5s
    retries: 3

  logging:
    format: "json"
    level: "INFO"
    handlers:
      - "console"
      - "file"
    file:
      path: "/var/log/gis-service.log"
      max_size: 100MB
      backup_count: 5

security:
  ssl:
    enabled: true
    cert_path: "/etc/ssl/certs/gis-service.crt"
    key_path: "/etc/ssl/private/gis-service.key"

  authentication:
    method: "jwt"
    token_expiry: 3600
    refresh_token_expiry: 86400

  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20

resources:
  cpu:
    limit: "2"
    request: "1"
  memory:
    limit: "4Gi"
    request: "2Gi"
  storage:
    limit: "10Gi"
    request: "5Gi"

alerting:
  channels:
    email:
      enabled: true
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      from_address: "alerts@lexos.com"
      to_addresses:
        - "admin@lexos.com"
    slack:
      enabled: true
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#gis-alerts"

  thresholds:
    cpu_usage: 80
    memory_usage: 85
    disk_usage: 90
    error_rate: 5
    response_time: 1000 