global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        service: dj-agent
      receiver: 'dj-alerts'
      continue: true
    - match:
        alertname: HighAudioLatency
      receiver: 'dj-critical'
      continue: true
    - match:
        alertname: GPUUtilizationHigh
      receiver: 'dj-critical'
      continue: true
    - match:
        alertname: AudioBufferUnderrun
      receiver: 'dj-critical'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ .CommonAnnotations.dashboard }}'
          - type: button
            text: 'Runbook'
            url: '{{ .CommonAnnotations.runbook }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#critical-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ .CommonAnnotations.dashboard }}'
          - type: button
            text: 'Runbook'
            url: '{{ .CommonAnnotations.runbook }}'

  - name: 'dj-alerts'
    slack_configs:
      - channel: '#dj-alerts'
        send_resolved: true
        title: '{{ template "slack.dj.title" . }}'
        text: '{{ template "slack.dj.text" . }}'
        actions:
          - type: button
            text: 'View DJ Dashboard'
            url: '{{ .CommonAnnotations.dj_dashboard }}'
          - type: button
            text: 'DJ Runbook'
            url: '{{ .CommonAnnotations.dj_runbook }}'

  - name: 'dj-critical'
    slack_configs:
      - channel: '#dj-critical'
        send_resolved: true
        title: '{{ template "slack.dj.critical.title" . }}'
        text: '{{ template "slack.dj.critical.text" . }}'
        actions:
          - type: button
            text: 'View DJ Dashboard'
            url: '{{ .CommonAnnotations.dj_dashboard }}'
          - type: button
            text: 'DJ Runbook'
            url: '{{ .CommonAnnotations.dj_runbook }}'
          - type: button
            text: 'Emergency Stop'
            url: '{{ .CommonAnnotations.emergency_stop }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl' 