name: Deploy to RunPod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger RunPod Sync
        run: |
          curl -X POST https://api.runpod.io/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}" \
            -d '{
              "query": "mutation { podRestart(podId: \"ogir1qt2d86ob1\") { id status } }"
            }' 